### ISSUE TITLE
Create a small dataset with realistic data about faces

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#10]
**Description:**
Create at least 100 images with different lightning and position of head

**Tasks:**
- [x] Create a script to create data
- [x] Save the created images to folder
- [x] Add functionality of randomness
- [x] Add basic script, which creates at least 50 images with different angles and lightning
- [x] Create mathematical functions to find theta and phi.
- [x] Implement randomization to both angles and lightning simultaneously
