### ISSUE TITLE
Create a script, which can compute angles

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#12]
**Description:**
Create a script, which can compute different angles from the image file name

**Tasks:**
- [x] Mathematical part (radius, phi, theta, x, y, z)
- [x] Reading files from a certain folder
- [x] Separating different keys for separate formats
- [x] Ignore test files
- [x] Verify angle calculations
