### ISSUE TITLE
Plan Sprint 3

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#15]
**Description:**
Plan tasks of Sprint 3 and set goals

**Tasks:**
- [x] Set tasks
- [x] Change labels to Sprint 3
- [x] Set labels and projects to task
- [x] Create label and milestone for Sprint 4
