### ISSUE TITLE
Write a data creation part

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#16]
**Description:**
Write about how training and testing data is generated

**Tasks:**
- [x] Environments (Spyder, Anaconda, Python)
- [x] Libraries (face3D, math, etc.)
- [x] Angle computation with given data in 3D space
- [x] Example and sizes of training and testing
- [ ] Add it to thesis
