### ISSUE TITLE
Write about Keras CNN part

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#17]
**Description:**
Write about Machine learning technique CNN, own implementation

**Tasks:**
- [x] Theory about CNN (short)
- [x] Own implementation (input, layers, output)
- [ ] Add it to thesis
