### ISSUE TITLE
Create a visualization, which visualises estimation and GT

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#26]
**Description:**
Create a visualization for CNN testing, which computes and visualizes estimated angle with ground truth (real angle).

**Tasks:**
- [x] Show image
- [x] Add estimation line
- [x] Add ground truth line
- [x] Add randomization for automated or easy-to-use runs
