### ISSUE TITLE
Write a short report of things tried in network

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#30]
**Description:**
Write a short report of things tried in network

**Tasks:**
- [x] Input format (masks, RGB, grayscale)
- [x] Network structure (batch normalization, dropout)
- [x] Performance
- [x] Limitations in an environment
- [x] Images to visualize
