### ISSUE TITLE
Test different models by performance

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#31]
**Description:**
Test and evaluate performances of different networks and different input data

**Test rounds**
* 10 * 100 test rounds in range 0, 1000
* 10 * 100 test rounds in range 0, max

**Types**
* normal RGB
* masked RGB
* grayscale

**Keep track of**
* minimum average angle
* maximum average angle
* minimum average angle dividation between angle thresholds
* parameter amount
* w, h, d (input size)

**Tasks:**
- [x] 2 best performing grayscales
- [x] 2 best performing masked RGBs
- [x] 2 best performing RGBs
