### ISSUE TITLE
Add visualization for node activations

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#33]
**Description:**
Visualize node activations in between of input and output.

**Tasks:**
- [x] Create a function to visualize node activation
- [x] Test the function
- [x] Push to Github
