### ISSUE TITLE
Create a simple code for testing model with image data

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#36]
**Description:**
Create a simple code for testing model with image data

**Tasks:**
- [x] load model
- [x] predict
- [x] read from folder
- [x] comments on parameters
- [x] Push to Github
