### ISSUE TITLE
Create a predict tool

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#39]
**Description:**
Create predict tool to evaluate angle from image (source unknown)

**Tasks:**
- [x] Load model
- [x] Get and set input size
- [x] RGB to grayscale function
- [x] Preprocess image
- [x] Visualize result
- [x] Read from folder possibility
