### ISSUE TITLE
Write .pgm image handler

### ISSUE THREAD

**Issue by NemoHostem** [NemoHostem/CNN_Source_of_Light#40]
**Description:**
Write .pgm image handler. Images should be saved in grayscale to given folder

**Tasks:**
- [x] Face detection
- [x] Reading .pgm file
- [x] Saving images to folder
- [x] Automatically running from single folder
- [x] Push to Github
- [x] Visualization
- [x] Histogram equalization
